### ISSUE TITLE
App Crashes when back button is Clicked

### ISSUE THREAD

**Issue by mathemandy** [demistry/CryptoCur_App#1]
#### Expected behavior
Pressing the back button should take the user to the previous Activity, or the Parent activity if there is one.

#### Actual behavior
After making a conversion the back button on the toolbar crashes the Application.

#### How to reproduce
- Step 1 : Download App
- Step 2 : Launch App and click on Continue button  
- Step 3 : Create an Exchange Card using the Floating Action button with the **+** Sign
- Step 4 : Select the created card to perform and exchange 
- Step 5 : Enter a value to calculate the exchange rate
- step 6 : After exchange rate is calculated, Press the back button
***
* Phone : Infinix Note 4  
* Operating system: Android Nougat

#### Recording Of The Bug
https://youtu.be/M1j6LLjJutw
    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@mathemandy/app-crashes-when-back-button-is-clicked">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by demistry** [comment]
Thank you for detecting this bug, it has been resolved. Check the commit on this link https://github.com/demistry/CryptoCur_App/commit/c0a5218056a8a039f03a5c990cac3c0220443c87
